// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPostSwapDrawTilesRequest = {
  tile_id_a: number;
  tile_id_b: number;
};
