// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPostCreateMeldRequest = {
  is_concealed: boolean;
  is_upgrade: boolean;
  player_id: string;
  tiles: Array<number>;
};
