// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type AuthInfoSummary = { provider: Provider; username: null | string };
