// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dragon } from "./Dragon";

export type DragonTile = { id: number; value: Dragon };
