// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WallSegment } from "./WallSegment";
import type { Wind } from "./Wind";

export type DrawWall = {
  dead_wall: WallSegment;
  segments: { [key in Wind]: WallSegment };
  unordered: Array<number>;
};
