// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flower } from "./Flower";

export type FlowerTile = { id: number; value: Flower };
