// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameSettingsSummary = {
  ai_enabled: boolean;
  auto_sort: boolean;
  auto_stop_claim_meld: boolean;
  discard_wait_ms: null | number;
  fixed_settings: boolean;
  last_discard_time: string;
};
