// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GamePhase } from "./GamePhase";
import type { GameStyle } from "./GameStyle";
import type { Players } from "./Players";
import type { Round } from "./Round";
import type { Score } from "./Score";
import type { Table } from "./Table";

export type Game = {
  id: string;
  name: string;
  phase: GamePhase;
  players: Players;
  round: Round;
  score: Score;
  style: GameStyle;
  table: Table;
  version: string;
};
