// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameSettings = {
  ai_enabled: boolean;
  auto_sort_players: Array<string>;
  auto_stop_claim_meld: Array<string>;
  discard_wait_ms: null | number;
  fixed_settings: boolean;
  last_discard_time: bigint;
};
