// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandTile } from "./HandTile";

export type Hand = { list: Array<HandTile> };
