// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandTile } from "./HandTile";
import type { KongTile } from "./KongTile";

export type Hand = { kong_tiles: Array<KongTile>; list: Array<HandTile> };
