// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandMeld } from "./HandMeld";

export type HandMelds = { melds: Array<HandMeld>; tiles_without_meld: number };
