// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStyle } from "./GameStyle";
import type { HandTile } from "./HandTile";

export type Hand = { list: Array<HandTile>; style: GameStyle | null };
