// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OtherPlayerHand } from "./OtherPlayerHand";

export type OtherPlayerHands = { [key: string]: OtherPlayerHand };
