// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hand } from "./Hand";

export type OtherPlayerHand = { tiles: number; visible: Hand };
