// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandTileStat } from "./HandTileStat";
import type { PossibleMeld } from "./PossibleMeld";
import type { ServicePlayerSummary } from "./ServicePlayerSummary";
import type { VisibleMeld } from "./VisibleMeld";
import type { Wind } from "./Wind";

export type PlayingExtras = {
  can_claim_tile: boolean;
  can_discard_tile: boolean;
  can_draw_tile: boolean;
  can_pass_round: boolean;
  can_pass_turn: boolean;
  can_say_mahjong: boolean;
  dealer_player: null | ServicePlayerSummary;
  hand_stats: { [key: number]: HandTileStat };
  players_visible_melds: { [key: string]: Array<VisibleMeld> };
  players_winds: { [key: string]: Wind };
  playing_player: null | ServicePlayerSummary;
  possible_melds: Array<PossibleMeld>;
  turn_player: null | ServicePlayerSummary;
};
