// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PossibleMeld = {
  discard_tile: null | number;
  is_concealed: boolean;
  is_mahjong: boolean;
  is_upgrade: boolean;
  player_id: string;
  tiles: Array<number>;
};
