// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Queries =
  | {
      ai_player_names: Array<string> | null;
      auto_sort_own: boolean | null;
      dead_wall: boolean | null;
      player_id: string;
      type: "UserCreateGame";
    }
  | {
      game_id: string;
      game_version: string;
      player_id: string;
      type: "UserDrawTile";
    }
  | {
      game_id: string;
      is_concealed: boolean;
      is_upgrade: boolean;
      player_id: string;
      tiles: Array<number>;
      type: "UserCreateMeld";
    }
  | {
      game_id: string;
      player_id: string;
      set_id: string;
      type: "UserBreakMeld";
    }
  | { game_id: string; player_id: string; type: "UserMovePlayer" }
  | { game_id: string; tile_id: number; type: "UserDiscardTile" }
  | { type: "UserGetDashboard" };
