// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Wind } from "./Wind";

export type RoundSummary = {
  consecutive_same_seats: number;
  dealer_player_index: number;
  discarded_tile: null | number;
  east_player_index: number;
  player_index: number;
  wind: Wind;
};
