// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Season } from "./Season";

export type SeasonTile = { id: number; value: Season };
