// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { GameSettings } from "./GameSettings";
import type { ServicePlayer } from "./ServicePlayer";

export type ServiceGame = {
  created_at: bigint;
  game: Game;
  players: { [key: string]: ServicePlayer };
  settings: GameSettings;
  updated_at: bigint;
};
