// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServicePlayer = {
  created_at: string;
  id: string;
  is_ai: boolean;
  name: string;
};
