// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettingsSummary } from "./GameSettingsSummary";
import type { GameSummary } from "./GameSummary";
import type { ServicePlayerSummary } from "./ServicePlayerSummary";

export type ServiceGameSummary = {
  game_summary: GameSummary;
  players: { [key: string]: ServicePlayerSummary };
  settings: GameSettingsSummary;
};
