// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Board } from "./Board";
import type { BonusTiles } from "./BonusTiles";
import type { DrawWall } from "./DrawWall";
import type { Hands } from "./Hands";

export type Table = {
  board: Board;
  bonus_tiles: BonusTiles;
  draw_wall: DrawWall;
  hands: Hands;
};
