// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragonTile } from "./DragonTile";
import type { FlowerTile } from "./FlowerTile";
import type { SeasonTile } from "./SeasonTile";
import type { SuitTile } from "./SuitTile";
import type { WindTile } from "./WindTile";

export type Tile =
  | { Dragon: DragonTile }
  | { Flower: FlowerTile }
  | { Season: SeasonTile }
  | { Suit: SuitTile }
  | { Wind: WindTile };
