// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthInfoSummary } from "./AuthInfoSummary";
import type { DashboardGame } from "./DashboardGame";
import type { DashboardPlayer } from "./DashboardPlayer";

export type UserGetDashboardResponse = {
  auth_info: AuthInfoSummary;
  player: DashboardPlayer;
  player_games: Array<DashboardGame>;
  player_total_score: number;
};
