// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPostSortHandRequest = {
  game_version: string;
  player_id: string;
  tiles: Array<number> | null;
};
