// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSettingsSummary } from "./GameSettingsSummary";

export type UserPostSetGameSettingsRequest = {
  player_id: string;
  settings: GameSettingsSummary;
};
