// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceGameSummary } from "./ServiceGameSummary";

export type UserPostAIContinueResponse = {
  changed: boolean;
  service_game_summary: ServiceGameSummary;
};
