// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPostCreateGameRequest = {
  ai_player_names: Array<string> | null;
  auto_sort_own: boolean | null;
  dead_wall: boolean | null;
  player_id: string;
};
