pub const ENV_AUTH_JWT_SECRET_KEY: &str = "MAHJONG_JWT_SECRET";

pub const ENV_SQLITE_DB_KEY: &str = "MAHJONG_STORAGE_SQLITE_DB";

pub const ENV_LOGGER_LEVEL: &str = "MAHJONG_LOGGER_LEVEL";

pub const ENV_GRAPHQL_SOURCE: &str = "MAHJONG_GRAPHQL_SOURCE";

pub const ENV_GITHUB_CLIENT_ID: &str = "GITHUB_CLIENT_ID";

pub const ENV_GITHUB_SECRET: &str = "GITHUB_SECRET";

pub const ENV_FRONTEND_URL: &str = "FRONTEND_URL";
