pub const ENV_AUTH_JWT_SECRET_KEY: &str = "MAHJONG_JWT_SECRET";

pub const ENV_FILE_STORAGE_KEY: &str = "MAHJONG_STORAGE_FILE";

pub const ENV_SQLITE_DB_KEY: &str = "MAHJONG_STORAGE_SQLITE_DB";

pub const ENV_LOGGER_LEVEL: &str = "MAHJONG_LOGGER_LEVEL";

pub const GRAPHQL_SOURCE: &str = "MAHJONG_GRAPHQL_SOURCE";
