[package]
name = "mahjong_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.155", features = ["derive"] }
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics", "js"] }
wasm-bindgen = "0.2.84"
