[workspace]
members = [
    "cli",
    "mahjong_core",
    "service",
    "service_contracts",
    "web_lib"
]
resolver = "1"

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true
strip = true
panic = "abort"
