[workspace]
members = [
    "mahjong_core",
    "scripts",
    "service",
    "service_contracts",
    "tui_client",
    "web_lib"
]

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true
strip = true
panic = "abort"
