version: "3.9"

services:
  server:
    image: igncp/mahjong_service:${DOCKER_TAG}
    environment:
      MAHJONG_JWT_SECRET: ${MAHJONG_JWT_SECRET}
      MAHJONG_STORAGE_FILE: /app/data/mahjong.json
      MAHJONG_STORAGE_SQLITE_DB: /app/data/mahjong.db
    volumes:
      - ./data:/app/data
    ports:
      - 3000:3000
