FROM debian:12-slim
USER root

# libssl3 needs unstable
RUN echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y libssl-dev ca-certificates libssl3 postgresql

RUN useradd -m -s /bin/bash rust \
  && mkdir -p /app \
  && chown -R rust:rust /app

USER rust
WORKDIR /app

COPY --chown=rust:rust service/target/release/mahjong_service .

CMD ./mahjong_service
