FROM nginx:1.25.4

# docker run --rm -it --net host -v $PWD/letsencrypt:/etc/letsencrypt nginx:1.25.4 bash
  # apt update && apt install -y certbot python3-certbot-nginx
  # certbot certonly --nginx -d mahjong-rust.com

COPY web_client/out/ /var/www/html/
COPY web_client/nginx.conf /etc/nginx/conf.d/default.conf
