version: "3.9"

services:
  server:
    image: igncp/mahjong_service:${DOCKER_TAG}
    environment:
      MAHJONG_ADMIN_PASS: ${MAHJONG_ADMIN_PASS}
      MAHJONG_JWT_SECRET: ${MAHJONG_JWT_SECRET}
      MAHJONG_LOGGER_LEVEL: ${MAHJONG_LOGGER_LEVEL}
      MAHJONG_STORAGE_FILE: /app/data/mahjong.json
      MAHJONG_STORAGE_SQLITE_DB: /app/data/mahjong.db
    volumes:
      - ./data:/app/data
  front:
    image: igncp/mahjong_front:${DOCKER_TAG}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
