version: "3.9"

services:
  server:
    image: igncp/mahjong_service:${DOCKER_TAG}
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      MAHJONG_ADMIN_PASS: ${MAHJONG_ADMIN_PASS}
      MAHJONG_JWT_SECRET: ${MAHJONG_JWT_SECRET}
      MAHJONG_LOGGER_LEVEL: ${MAHJONG_LOGGER_LEVEL}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./mahjong_db:/var/lib/postgresql/data
    restart: always
  front:
    image: igncp/mahjong_front:${DOCKER_TAG}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
