on:
  workflow_run:
    workflows: ["Checks"]
    types: [completed]
    branches:
      - 'main'

name: Deploy

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build script
        run: |
          cargo build --release -p scripts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build docker image
        env:
          NEXT_PUBLIC_SERVICE_URL: https://mahjong-rust.com/api
        run: |
          ./target/release/scripts docker
