name: Deploy

on:
  workflow_run:
    workflows: ["Checks"]
    types: [completed]
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      NEXT_PUBLIC_SERVICE_URL:
        required: false
        description: ""
        default: "https://mahjong-rust.com/api"
      NO_K8S_DEPLOY:
        required: false
        description: ""
        default: ""

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build script
        run: |
          touch ./scripts/nix/is-docker-ci
          nix develop path:$(pwd) -c rustup install stable
      - name: Build docker image
        env:
          DEPLOYMENT_LOCATION: ${{ secrets.DEPLOYMENT_LOCATION }}
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          NEXT_PUBLIC_GITHUB_CLIENT_ID: 5b79179dd44f90e1a63a
          NEXT_PUBLIC_SERVICE_URL: ${{ github.event.inputs.NEXT_PUBLIC_SERVICE_URL }}
          NO_K8S_DEPLOY: ${{ github.event.inputs.NO_K8S_DEPLOY }}
        run: |
          nix develop path:$(pwd) -c bash -c 'bash scripts/src/main.sh docker'
