on:
  workflow_run:
    workflows: ["Checks"]
    types: [completed]
    branches:
      - 'main'

name: Web

jobs:
  web:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build script
        run: |
          cargo build --release -p scripts
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build web
        run: |
          ./target/release/scripts web
